name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    env:
        SOLUTION_PATH: Marco.TestLibrary/Marco.TestLibrary.sln

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Pack NuGet package
        run: dotnet pack ${{ env.SOLUTION_PATH }} --configuration Release --output ./output
        
      - name: Publish NuGet package
        run: dotnet nuget push ./output/Marco.TestLibrary.1.0.0.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      