name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    env:
        SOLUTION_PATH: TestLibrary/TestLibrary.sln

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Display .NET SDK version
        run: dotnet --version

      - name: Clear NuGet Cache
        run: dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build project
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release

      - name: Pack NuGet package
        run: dotnet pack ${{ env.SOLUTION_PATH }} --configuration Release --output ./output
        
      - name: List output directory
        run: dir ./output
        
      - name: Install NuGet CLI
        run: |
          curl -o nuget.exe https://dist.nuget.org/win-x86-commandline/v6.0.0/nuget.exe

      - name: Publish NuGet package
        run: dotnet nuget push ./output/TestLibrary.1.0.0.nupkg --source nuget.org --api-key ${{ secrets.NUGET_API_KEY }}
      
      #- name: Publish NuGet package with NuGet CLI
      #  run: |
      #    nuget.exe push ./output/TestLibrary.1.0.0.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
